Fix various memory leaks in unifyfsd
LLNL/UnifyFS pull request #673
Opened 2021-08-19 20:48 UTC by rgmiller

This is a collection of commits that fix a variety of memory leaks in the daemon.
### Description

There were a variety of memory leaks found by running valgrind against the daemon.  Most of the leaks were minor (failing to release memory when the daemon exited), but a few did seem to leak memory continuously as the daemon ran.

### Motivation and Context

Resolves issue #660 

### How Has This Been Tested?

Testing was done by running unifyfsd within the context of valgrind on an Ubuntu workstation.  A few simple clients were run to read & write data and then the daemon was killed.  The resulting valgrind report was analyzed.

### Types of changes

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Testing (addition of new tests or update to current tests)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x ] My code follows the UnifyFS code style requirements.
- [ ] I have updated the documentation accordingly.
- [x ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x ] All commit messages are properly formatted.

2021-08-20 18:50 UTC, MichaelBrim requested changes
For the `unifyfs_inode_tree_clear()` changes, use`unifyfs_inode_destroy(oldnode)` instead of freeing the allocations inside the inode directly.

2021-08-20 19:05 UTC, MichaelBrim commented on server/src/unifyfs_server.c
> +    ret = ABT_mutex_free(&app_configs_abt_sync);
Not sure about this, but I think if `margo_finalize()` is being called as part of `margo_server_rpc_finalize()` above, and we're relying on Margo to init/fini Argobots, then we may not be able to safely call any ABT_xxx methods after that.

2021-08-23 20:30 UTC, rgmiller commented
> For the `unifyfs_inode_tree_clear()` changes, use`unifyfs_inode_destroy(oldnode)` instead of freeing the allocations inside the inode directly.

That will require some changes in unifyfs_inode.c:  `unifyfs_inode_destroy()` is currently a static function.  If we want to call it from `unifyfs_inode_tree_clear()`, we'd have to change that.  I don't know if that will cause issues elsewhere or not.

2021-09-03 11:50 UTC, MichaelBrim commented
@rgmiller if you are happy with the current code, please do a rebase of this versus current dev and squash down to one commit.

2021-09-03 13:40 UTC, rgmiller commented
> @rgmiller if you are happy with the current code, please do a rebase of this versus current dev and squash down to one commit.

@MichaelBrim Done - sort of.  It seems to have squashed down to 4 commits.  The fskv_init thing has already been merged in and two others were merges of the latest dev branch changes back into the dev branch on my fork.  I'm guessing that's why they didn't get squashed.  Why the fskv_init commit is showing up at all still baffles me.

2021-09-03 19:53 UTC, rgmiller commented
I resolved the conflict in unifyfs_inode.c.  Not sure about unifyfs_fid.c.

2021-09-03 20:11 UTC, MichaelBrim commented
@rgmiller Because of the intermediate merges, it doesn't appear there is an easy way to get rgmiller:dev back in a state where there is a single commit versus LLNL:dev. My suggestion would be to start over with a new branch based on LLNL:dev and re-do the necessary changes in that branch, and then submit a new PR.

2021-09-03 20:16 UTC, rgmiller commented
What about just squashing the commits during the merge?  GitHub has an option to do that, doesn't it?

2021-09-03 20:42 UTC, MichaelBrim commented
Currently this has a bunch of "changes" unrelated to your memory leak fixes, which makes it hard to track where the code came from and why it changed. In general though, we try to avoid having merge commits in the history. I can help clean this up if you want me to.

2021-09-08 15:30 UTC, rgmiller commented
OK, I've created a new branch (in my forked repo) with just the memory leak fixes.  I'll close this pull request and create a new one using the new branch.

2021-09-08 15:30 UTC, closed without merging