Use New MD5 API Function
LLNL/UnifyFS pull request #791
Opened 2023-08-11 20:05 UTC by rgmiller

### Description

Change the OpenSSL MD5 API function from the deprecated `MD5` to the new `EVP_Digest`.  Also added a check for `EVP_Digest` to the configure script.  This PR fixes issue #723.

### Motivation and Context

As of OpenSSL v3, the `MD5` function is deprecated and generates a warning at compile time if it's used.

### How Has This Been Tested?

Ran existing unit tests on an Ubuntu 22.04 system.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Testing (addition of new tests or update to current tests)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [x] My code follows the UnifyFS code style requirements.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] All commit messages are properly formatted.

2023-08-14 17:16 UTC, MichaelBrim requested changes

2023-08-14 19:57 UTC, MichaelBrim commented on m4/openssl.m4
> +  AC_CHECK_LIB([crypto], [EVP_Digest],
just noting group consensus to make this move to `PKG_CHECK_MODULES(libcrypto)`

2023-08-14 20:25 UTC, rgmiller commented
@MichaelBrim That's interesting.  Those functions don't generate warnings at build time.  Maybe they aren't deprecated the way `MD5()` is?  I'll take a look...

2023-08-22 20:55 UTC, rgmiller commented
Mystery sort-of solved:  I don't see deprecation warnings for the functions in `unifyfs-stage-transfer.c` because in my build environment, `unifyfs-stage` is built using the spack-provided version of OpenSSL (which is v1.1.1 and hasn't yet deprecated the functions).

Now the new question is: why is one part of UnifyFS built against the system-provided OpenSSL, while another part is build against a spack-built version?

2023-09-11 19:17 UTC, MichaelBrim approved these changes

2023-09-11 19:18 UTC, merged